name: Movietale Continuous Integration
on: [push]
jobs:
  check_code_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
        - run: cd server
        - run: npm ci
        - run: npm test
        - run: npm start