name: Movietale Continuous Integration
on: [push]
jobs:
  check_push_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Install server dependancies
        run: cd server && npm ci
      - name: Install client dependancies
        run: cd client && npm ci
      - name: Build docker Containers
        run: docker-compose -f docker-compose.yml up --build
      - name: Run Mocha tests
        run: cd server && npm test
      - name: Stop Containers
        if: always()
        run: docker-compose down